extends Area2D

var enemy_type: String = "shards"

@onready var shard_player = $AnimationPlayer
@onready var child_node = get_node("Player")

func hit_detection():
    #print("Shift!")
    #var tween = create_tween().set_parallel(true)
    #tween.tween_property($Sprite, "position:y", 4, 0.1)
    #tween.tween_property($Sprite, "position:y", 0, 0.05)
    #await tween.finished
    #EventBus.set_shield.emit(-1)
    shard_player.pause()
    await get_tree().create_timer(0.5).timeout
    shard_player.play()
